<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_postcode</name>
   <tag></tag>
   <elementGuidId>bfebb656-7405-460c-ab93-2e590224f0e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_postcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_postcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c34c3e6-b0a4-45b3-8420-2a2d8b24417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8127b806-0b5c-4dc8-8d5c-c871d01f3f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>ee09a5ff-e860-48d7-b901-91c6673db57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>01b35e72-6b18-465c-80ef-8ae172067ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>f1d09b7d-fc20-4397-a0da-bc04125aa7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>70000</value>
      <webElementGuid>771a305a-f9de-4bc5-875e-5bf0503c8ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>476d6b2e-9273-410a-948e-b0b864803c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_postcode&quot;)</value>
      <webElementGuid>43c912e4-72d1-4729-b539-f2474054b711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_postcode']</value>
      <webElementGuid>3c4ce386-04a9-493b-8656-e139eaee9471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_postcode_field']/span/input</value>
      <webElementGuid>af449c5d-d78f-473f-8121-72e2e86b0e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/span/input</value>
      <webElementGuid>0e236534-991e-4a30-923f-689291dabbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_postcode' and @id = 'billing_postcode']</value>
      <webElementGuid>8a2187c6-f432-4e93-9c39-8ea2b1a40481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
