<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Last name</name>
   <tag></tag>
   <elementGuidId>8c9201f4-c116-471a-a4d2-8a0090a9cb42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_last_name_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_last_name_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9e76f287-2c72-480b-9ba6-7fa4c3860fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-row form-row-last validate-required</value>
      <webElementGuid>14cacd97-a19e-407e-8876-dbe123f77df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_last_name_field</value>
      <webElementGuid>ef2ec981-c442-4c40-94c8-de67e5748183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-priority</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3f26b6bb-1959-4369-827b-33d6fbab130b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last name *</value>
      <webElementGuid>524fca22-34a2-4aab-a70c-380de02e257c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_last_name_field&quot;)</value>
      <webElementGuid>39d39050-8dc9-4733-b60f-3862827218f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='billing_last_name_field']</value>
      <webElementGuid>b62745b7-d0d4-434a-9132-920b91904e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_details']/div/div/div/p[2]</value>
      <webElementGuid>36e0a37b-31ee-47c4-9c5e-f34b42721a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::p[1]</value>
      <webElementGuid>f305432c-d68f-4568-a1b3-44945bbc330a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p[2]</value>
      <webElementGuid>5dea164b-fe64-4268-ba04-9527f23893f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'billing_last_name_field' and (text() = 'Last name *' or . = 'Last name *')]</value>
      <webElementGuid>78e4e042-2402-4c27-aead-e029330fe09a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
